import Image from "@/components/app-image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getOmdbSeasonRatings } from "@/lib/external-ratings";
import { getMedia, getSeason, imageUrl } from "@/lib/tmdb";

export default async function AllEpisodesPage({ params }: { params: Promise<{ kind: string; id: string }> }) {
  const { kind, id } = await params; if (kind !== "show") notFound(); const show = await getMedia("show", Number(id)); const imdbId = (show.raw as any).external_ids?.imdb_id as string | undefined;
  const seasons = await Promise.all(show.seasons.map(summary => getSeason(show.id, summary.seasonNumber))); const omdb = new Map<number, Awaited<ReturnType<typeof getOmdbSeasonRatings>>>(); const omdbResults = await Promise.all(seasons.map(season => getOmdbSeasonRatings(imdbId, season.seasonNumber))); seasons.forEach((season, index) => omdb.set(season.seasonNumber, omdbResults[index]));
  const rated = seasons.flatMap(season => season.episodes.map(episode => { const imdb = omdb.get(season.seasonNumber)?.find(item => item.episode === episode.episodeNumber)?.imdbRating ?? null; return { season: season.seasonNumber, episode, score: imdb ?? episode.voteAverage, source: imdb ? "IMDb" : "TMDB" }; })).filter(item => item.score > 0).sort((a, b) => b.score - a.score); const maxEpisodes = Math.max(0, ...seasons.map(season => season.episodes.length));
  return <main className="page"><div className="shell"><Link className="text-link" href={`/title/show/${id}`}>← Back to {show.title}</Link><div className="episodes-page-heading"><div><div className="eyebrow">Every chapter, compared</div><h1 className="display">Episodes & ratings</h1><p className="overview">Browse every season, jump to an episode, or scan the rating table. IMDb ratings are used where OMDb supplies them; otherwise the cell uses TMDB.</p></div>{show.posterPath && <Image src={imageUrl(show.posterPath, "w300")!} width={120} height={180} alt="" />}</div>
    <section className="section compact-section"><div className="section-head"><div><div className="eyebrow">Highest audience scores</div><h2 className="display">Top-rated episodes</h2></div></div><div className="top-episode-grid">{rated.slice(0, 6).map(item => <Link href={`/title/show/${id}/season/${item.season}/episode/${item.episode.episodeNumber}`} key={`${item.season}-${item.episode.id}`}><span>Top rated</span><strong>S{item.season}.E{item.episode.episodeNumber} · {item.episode.name}</strong><small>{item.score.toFixed(1)}/10 {item.source}</small></Link>)}</div></section>
    <section className="section compact-section"><div className="section-head"><div><div className="eyebrow">Season × episode</div><h2 className="display">Ratings table</h2></div></div><div className="episode-matrix-scroll"><table className="episode-matrix"><thead><tr><th>Season</th>{Array.from({ length: maxEpisodes }, (_, index) => <th key={index}>E{index + 1}</th>)}</tr></thead><tbody>{seasons.map(season => <tr key={season.id}><th><a href={`#season-${season.seasonNumber}`}>S{season.seasonNumber}</a></th>{Array.from({ length: maxEpisodes }, (_, index) => { const episode = season.episodes[index]; if (!episode) return <td className="empty" key={index} />; const imdb = omdb.get(season.seasonNumber)?.find(item => item.episode === episode.episodeNumber)?.imdbRating; const score = imdb ?? episode.voteAverage; return <td key={episode.id}><Link title={`${episode.name} · ${imdb ? "IMDb" : "TMDB"}`} href={`/title/show/${id}/season/${season.seasonNumber}/episode/${episode.episodeNumber}`}>{score ? score.toFixed(1) : "—"}</Link></td>; })}</tr>)}</tbody></table></div></section>
    {seasons.map(season => <section className="section episode-browser-season" id={`season-${season.seasonNumber}`} key={season.id}><div className="section-head"><div><div className="eyebrow">{season.airDate?.slice(0, 4) ?? "Year TBA"}</div><h2 className="display">{season.name}</h2></div><Link className="text-link" href={`/title/show/${id}/season/${season.seasonNumber}`}>Season details →</Link></div><div className="episode-browser-list">{season.episodes.map(episode => { const imdb = omdb.get(season.seasonNumber)?.find(item => item.episode === episode.episodeNumber)?.imdbRating; return <Link href={`/title/show/${id}/season/${season.seasonNumber}/episode/${episode.episodeNumber}`} key={episode.id}><div className="episode-browser-art">{episode.stillPath && <Image src={imageUrl(episode.stillPath, "w500")!} alt="" fill sizes="220px" />}</div><div><strong>S{season.seasonNumber}.E{episode.episodeNumber} · {episode.name}</strong><p>{episode.overview || "No description available."}</p><span>{episode.airDate ?? "TBA"} · ★ {(imdb ?? episode.voteAverage).toFixed(1)} {imdb ? "IMDb" : "TMDB"}</span></div></Link>; })}</div></section>)}
  </div></main>;
}
