import { redirect } from "next/navigation";
import { InfiniteRecommendationGrid } from "@/components/infinite-recommendation-grid";
import { ensureRecommendations, recommendationPage } from "@/lib/recommendations";
import { getGenres } from "@/lib/tmdb";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { withCommunityRatings } from "@/lib/community-ratings";

type Filters = { kind?: string; genre?: string; year?: string; hideWatched?: string; hideListed?: string };
export default async function Recommendations({ searchParams }: { searchParams: Promise<Filters> }) {
  const params = await searchParams; const supabase = await createSupabaseServerClient(); const user = supabase ? (await supabase.auth.getUser()).data.user : null; if (!user || !supabase) redirect("/login");
  await ensureRecommendations(user.id); const filters = { kind: params.kind, genre: params.genre, year: params.year, hideWatched: params.hideWatched !== "0", hideListed: params.hideListed === "1" }; const [genres, result] = await Promise.all([getGenres(), recommendationPage(supabase, user.id, filters)]); const rated = await withCommunityRatings(result.items.map(entry => entry.item), supabase); const initial = result.items.map((entry, index) => ({ ...entry, item: rated[index] })); const query = new URLSearchParams({ ...(params.kind ? { kind: params.kind } : {}), ...(params.genre ? { genre: params.genre } : {}), ...(params.year ? { year: params.year } : {}), hideWatched: filters.hideWatched ? "1" : "0", hideListed: filters.hideListed ? "1" : "0" }).toString();
  return <main className="page"><div className="shell"><div className="eyebrow">Calculated from your actual taste</div><h1 className="display page-title">For you</h1><p className="overview recommendation-intro">Personal picks shaped by your ratings, favorites, watch history and Trakt activity.</p>
    <form className="recommendation-filter"><select className="select" name="kind" defaultValue={params.kind ?? ""}><option value="">Movies & series</option><option value="movie">Movies</option><option value="show">Series</option></select><select className="select" name="genre" defaultValue={params.genre ?? ""}><option value="">Every genre</option>{genres.map(genre => <option key={genre.id} value={genre.id}>{genre.name}</option>)}</select><input className="input" name="year" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="Release year" defaultValue={params.year} /><label className="filter-checkbox"><input type="hidden" name="hideWatched" value="0" /><input name="hideWatched" value="1" type="checkbox" defaultChecked={filters.hideWatched} /> Hide watched</label><label className="filter-checkbox"><input name="hideListed" value="1" type="checkbox" defaultChecked={filters.hideListed} /> Hide titles in my lists</label><button className="button accent">Update</button></form>
    {initial.length ? <InfiniteRecommendationGrid key={query} initial={initial} nextCursor={result.nextCursor} query={query} total={result.total} /> : <div className="empty-state"><h2 className="display">No matches today</h2><p className="muted">Relax a filter or allow watched and listed titles.</p></div>}
  </div></main>;
}
